unoegohh_retail_homepage:
    pattern:  /
    defaults: { _controller: UnoegohhRetailBundle:Default:index }

unoegohh_retail_feedback:
    pattern:  /feedback
    defaults: { _controller: UnoegohhRetailBundle:Default:feedback }

unoegohh_retail_feedback_ok:
    pattern:  /feedbackOk
    defaults: { _controller: UnoegohhRetailBundle:Default:feedbackOk }

unoegohh_retail_gallery:
    pattern:  /gallery
    defaults: { _controller: UnoegohhRetailBundle:Default:gallery }

unoegohh_retail_static_page:
    pattern:  /{url}
    defaults: { _controller: UnoegohhRetailBundle:Default:static }
    requirements:
        url: ".*"
