parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: ~
    database_name: building
    database_user: root
    database_password: root
    database_path: ~

    mail_to: unoegohh@gmail.com
    mail_from: hello@gmail.com
    mail_name: hello
