services:
   unoegohh.admin.admin.banner:
      class: Unoegohh\AdminBundle\Admin\BannerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Основное', label: 'Баннеры' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Banner, UnoegohhAdminBundle:Banner]
   unoegohh.admin.admin.page:
      class: Unoegohh\AdminBundle\Admin\PageAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Основное', label: 'Страницы' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Page, UnoegohhAdminBundle:Page]
   unoegohh.admin.admin.photo:
      class: Unoegohh\AdminBundle\Admin\PhotoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Галлерея', label: 'Фотографии' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Photo, UnoegohhAdminBundle:Photo]
   unoegohh.admin.admin.estateCat:
      class: Unoegohh\AdminBundle\Admin\EstateCategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Недвижимость', label: 'Категории' }
      arguments: [null, Unoegohh\AdminBundle\Entity\EstateCategory, UnoegohhAdminBundle:EstateCategory]
   unoegohh.admin.admin.estateCity:
      class: Unoegohh\AdminBundle\Admin\EstateCityAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Недвижимость', label: 'Города' }
      arguments: [null, Unoegohh\AdminBundle\Entity\EstateCity, UnoegohhAdminBundle:EstateCity]
   unoegohh.admin.admin.estate:
      class: Unoegohh\AdminBundle\Admin\EstateAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Недвижимость', label: 'Объекты' }
      arguments: [null, Unoegohh\AdminBundle\Entity\Estate, UnoegohhAdminBundle:Estate]
   unoegohh.admin.admin.estatePhoto:
      class: Unoegohh\AdminBundle\Admin\EstatePhotoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Недвижимость', label: 'Фото' }
      arguments: [null, Unoegohh\AdminBundle\Entity\EstatePhoto, UnoegohhAdminBundle:EstatePhoto]