parameters:
#    unoegohh_estate.example.class: Unoegohh\EstateBundle\Example

services:
#    unoegohh_estate.example:
#        class: %unoegohh_estate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
